### PR TITLE
Apply REUSE initiative practices

### PR DESCRIPTION
**Pull request by LeSpocky**
* Move all license texts to subfolder LICENSES
* Add unchanged MIT license text (with adapted copyright)
* Add License-Filename headers
* Add headers to CMakeLists
* Add "reuse compliant" badge to README.md
* Split MIT licenses, one for each copyright holder (group)

See https://reuse.software/practices/ on rationale for this.

### CODE REVIEW

**Comment by LeSpocky** [comment]
Please review. I'm not entirely happy with those splitted license files which just differ in copyright holder. And: the MIT license text is somehow redundant in `LICENSE.txt` and those files in the `LICENSES` subfolder now, maybe drop it from the "main license" file and just add a pointer hint there?

**Comment by penguineer** [comment]
I'd keep the LICENSE.txt as fallback license for anything that does not state a license.

**Comment by penguineer** [comment]
In general I am not too happy with this author and copyright thing. This is one project. What happens if contributions mix? Who has the copyright? 

Maybe there is a better license for the project?

**Comment by LeSpocky** [comment]
What some projects use is something like "The project xy team" or "The project xy conributers" as copyright holder. Maybe one could use Netz39 there, or maybe just use "Stefan Haun" everywhere in the project?

**Comment by penguineer** [comment]
I am pro the "Project XY Contributors" approach! 
Maybe we can list those in a Contributors.txt file?

**Comment by LeSpocky** [comment]
I tried to do a little research, and it seems to be complicated, but maybe I'm just mistaken by that. I found the following stackoverflow answer quite helpful: https://opensource.stackexchange.com/a/5511

So I would propose the following wording for _all_ included files:

```
Copyright 2017 Stefan Haun, Netz39 e.V., and mqtta contributors
```

Maybe variations like:

```
Copyright 2017 Stefan Haun, Netz39 e.V., et al.
```

or drop the „Netz39“?

For the future just adapt the years, end of discussion.

We could also add a `CONTRIBUTORS.txt`, but I'm fine listing them in `README.md` or getting them from version control.

**Comment by penguineer** [comment]
Okay, we can go with either
`Copyright 2017 Stefan Haun, Netz39 e.V., and mqtta contributors`
or
`Copyright 2017 The mqtta project team`

I am fine with both. There is no explicit team, so it may be problematic to reference a team here. As the stackoverflow comment said: The copyright only lists the copyright owners, but does not define them.

For convenience we can keep the contributors list in the README.md, as it is not normative anyway.

**Comment by LeSpocky** [comment]
I made the requested changes, please review.

**Pull request merged**
